name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ '3.x' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Run tests
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -e .
          pytest
      - name: Slack notification Failure
        uses: rtCamp/action-slack-notify@master
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: '#games-ci'
          SLACK_USERNAME: GitHub Actions
          SLACK_COLOR: '#a30200'
          SLACK_TITLE: Build failed
          SLACK_ICON: 'http://pluspng.com/img-png/allure-med-spa-vector-png-github-head-logo-logo-256.png'
      - name: Slack notification Success
        uses: rtCamp/action-slack-notify@master
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: '#games-ci'
          SLACK_USERNAME: GitHub Actions
          SLACK_COLOR: '#2eb886'
          SLACK_TITLE: Build passed
          SLACK_ICON: 'http://pluspng.com/img-png/allure-med-spa-vector-png-github-head-logo-logo-256.png'