name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ '3.x' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Run tests
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -e .
          pytest
      - name: Slack notification Failure
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: cemkiy/action-slacker@master
        with:
          channel: '#games-ci'
          icon_url: 'http://pluspng.com/img-png/allure-med-spa-vector-png-github-head-logo-logo-256.png'
          username: GitHub CI
          color: '#a30200'
          author_name: $GITHUB_ACTOR
      - name: Slack notification Success
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: cemkiy/action-slacker@master
        with:
          channel: '#games-ci'
          icon_url: 'http://pluspng.com/img-png/allure-med-spa-vector-png-github-head-logo-logo-256.png'
          username: GitHub CI
          color: '#2eb886'
          author_name: $GITHUB_ACTOR
          fallback: 'Required plain-text summary of the attachment.'
          pretext: 'Optional text that appears above the attachment block'
          author_link: 'http://jdoe.com/me/'
          author_icon: 'https://img.icons8.com/metro/26/000000/free-bsd.png'
          title: 'Slack API Documentation'
          title_link: 'https://api.slack.com/'
          text: 'Optional text that appears within the attachment'
          image_url: 'https://img.icons8.com/wired/64/000000/thumb-up.png'
          thumb_url: 'https://img.icons8.com/officel/16/000000/good-quality.png'
          footer: 'Slack API'
          footer_icon: 'https://img.icons8.com/dotty/80/000000/facebook-like.png'