name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ '3.x' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Run tests
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -e .
          pytest
      - name: Slack notification Failure
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: cemkiy/action-slacker@master
        with:
          channel: '#games-ci'
          icon_url: 'http://pluspng.com/img-png/allure-med-spa-vector-png-github-head-logo-logo-256.png'
          username: GitHub CI
          color: '#a30200'
          title: 'Build failed'
      - name: Slack notification Success
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: cemkiy/action-slacker@master
        with:
          channel: '#games-ci'
          icon_url: 'http://pluspng.com/img-png/allure-med-spa-vector-png-github-head-logo-logo-256.png'
          username: GitHub CI
          color: '#2eb886'
          title: 'Build passed'