name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ '3.x' ]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Run tests
        run: |
          python setup.py install
          source .envrc
          pytest --cov=wallet_lib --cov-fail-under=90.00 ./tests/
      - name: Slack notification Failure
        uses: rtCamp/action-slack-notify@master
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: "#games-ci"
          SLACK_USERNAME: GitHub CI
          SLACK_ICON: 'http://pluspng.com/img-png/allure-med-spa-vector-png-github-head-logo-logo-256.png'
          SLACK_COLOR: '#a30200'
          SLACK_TITLE: Message
          SLACK_MESSAGE: Build failed
      - name: Slack notification Success
        uses: rtCamp/action-slack-notify@master
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: "#games-ci"
          SLACK_USERNAME: GitHub CI
          SLACK_ICON: 'http://pluspng.com/img-png/allure-med-spa-vector-png-github-head-logo-logo-256.png'
          SLACK_COLOR: '#2eb886'
          SLACK_TITLE: Message
          SLACK_MESSAGE: Build passed
