name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ '3.x' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Run tests
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -e .
          pytest
      - name: Slack notification Failure
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: cemkiy/action-slacker@master
        with:
          channel: ${{ secrets.SLACK_CHANNEL }}
          icon_url: 'https://img.icons8.com/dusk/64/000000/thumbs-down.png'
          username: ${{ GITHUB_ACTOR }}
      - name: Slack notification Success
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: cemkiy/action-slacker@master
        with:
          channel: ${{ secrets.SLACK_CHANNEL }}
          icon_url: 'https://img.icons8.com/dusk/64/000000/facebook-like.png'
          username: ${{ GITHUB_ACTOR }}