name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  coverage:
    runs-on: ubuntu-18.04
    steps:
      - uses: cclauss/GitHub-Action-for-pytest@0.5.0